package gmoji

/**
	Font Awesome Emojis
	Versions
	{
		from 1.0 to 4.7 is available
	}
**/

const (
	all                     Gmoji = gmoji.bakeGmoji
	Glass                   Gmoji = "\uf000"
	Music                   Gmoji = "\uf001"
	Search                  Gmoji = "\uf002"
	EnvelopeOutlined        Gmoji = "\uf003"
	Heart                   Gmoji = "\uf004"
	Star                    Gmoji = "\uf005"
	StarOutlined            Gmoji = "\uf006"
	User                    Gmoji = "\uf007"
	Film                    Gmoji = "\uf008"
	ThLarge                 Gmoji = "\uf009"
	Th                      Gmoji = "\uf00a"
	ThList                  Gmoji = "\uf00b"
	Check                   Gmoji = "\uf00c"
	Times                   Gmoji = "\uf00d"
	SearchPlus              Gmoji = "\uf00e"
	SearchMnus              Gmoji = "\uf010"
	PowerOff                Gmoji = "\uf011"
	Signal                  Gmoji = "\uf012"
	Cog                     Gmoji = "\uf013"
	TrashOutlined           Gmoji = "\uf014"
	Home                    Gmoji = "\uf015"
	FileOutlined            Gmoji = "\uf016"
	ClockOutlined           Gmoji = "\uf017"
	Road                    Gmoji = "\uf018"
	Download                Gmoji = "\uf019"
	ArrowCircleOutlinedDown Gmoji = "\uf01a"
	ArrowCircleOutlinedUp   Gmoji = "\uf01b"
	Inbox                   Gmoji = "\uf01c"
	PlayCircleOutlined      Gmoji = "\uf01d"
	Repeat                  Gmoji = "\uf01e"
	Refresh                 Gmoji = "\uf021"
	ListAlt                 Gmoji = "\uf022"
	Lock                    Gmoji = "\uf023"
	Flag                    Gmoji = "\uf024"
	Headphones              Gmoji = "\uf025"
	VolumeOff               Gmoji = "\uf026"
	VolumeDown              Gmoji = "\uf027"
	VolumeUp                Gmoji = "\uf028"
	Qrcode                  Gmoji = "\uf029"
	Barcode                 Gmoji = "\uf02a"
	Tag                     Gmoji = "\uf02b"
	Tags                    Gmoji = "\uf02c"
	Book                    Gmoji = "\uf02d"
	Bookmark                Gmoji = "\uf02e"
	PrintEmoji              Gmoji = "\uf02f"
	Camera                  Gmoji = "\uf030"
	Font                    Gmoji = "\uf031"
	Bold                    Gmoji = "\uf032"
	Italic                  Gmoji = "\uf033"
	TextHeight              Gmoji = "\uf034"
	TextWidth               Gmoji = "\uf035"
	AlignLeft               Gmoji = "\uf036"
	AlignCenter             Gmoji = "\uf037"
	AlignRight              Gmoji = "\uf038"
	AlignJustify            Gmoji = "\uf039"
	List                    Gmoji = "\uf03a"
	Outdent                 Gmoji = "\uf03b"
	Indent                  Gmoji = "\uf03c"
	VideoCamera             Gmoji = "\uf03d"
	Picture                 Gmoji = "\uf03e"
	Pencil                  Gmoji = "\uf040"
	MapMarker               Gmoji = "\uf041"
	Adjust                  Gmoji = "\uf042"
	Tint                    Gmoji = "\uf043"
	PencilSquareOutlined    Gmoji = "\uf044"
	ShareSquareOutlined     Gmoji = "\uf045"
	CheckSquareOutlined     Gmoji = "\uf046"
	Arrows                  Gmoji = "\uf047"
	StepBackward            Gmoji = "\uf048"
	FastBackward            Gmoji = "\uf049"
	Backward                Gmoji = "\uf04a"
	Play                    Gmoji = "\uf04b"
	Pause                   Gmoji = "\uf04c"
	Stop                    Gmoji = "\uf04d"
	Forward                 Gmoji = "\uf04e"
	FastForward             Gmoji = "\uf050"
	StepForward             Gmoji = "\uf051"
	Eject                   Gmoji = "\uf052"
	ChevronLeft             Gmoji = "\uf053"
	ChevronRight            Gmoji = "\uf054"
	PlusCircle              Gmoji = "\uf055"
	MinusCircle             Gmoji = "\uf056"
	TimesCircle             Gmoji = "\uf057"
	CheckCircle             Gmoji = "\uf058"
	QuestionCircle          Gmoji = "\uf059"
	InfoCircle              Gmoji = "\uf05a"
	TimesCircleOutlined     Gmoji = "\uf05c"
	CheckCircleOutlined     Gmoji = "\uf05d"
	Ban                     Gmoji = "\uf05e"
	ArrowLeft               Gmoji = "\uf060"
	ArrowRight              Gmoji = "\uf061"
	ArrowUp                 Gmoji = "\uf062"
	ArrowDown               Gmoji = "\uf063"
	Share                   Gmoji = "\uf064"
	Expand                  Gmoji = "\uf065"
	Compress                Gmoji = "\uf066"
	Plus                    Gmoji = "\uf067"
	Minus                   Gmoji = "\uf068"
	Asterisk                Gmoji = "\uf069"
	ExclamationCircle       Gmoji = "\uf06a"
	Gift                    Gmoji = "\uf06b"
	Leaf                    Gmoji = "\uf06c"
	Fire                    Gmoji = "\uf06d"
	Eye                     Gmoji = "\uf06e"
	EyeSlash                Gmoji = "\uf070"
	ExclamationTriangle     Gmoji = "\uf071"
	Plane                   Gmoji = "\uf072"
	Calendar                Gmoji = "\uf073"
	Random                  Gmoji = "\uf074"
	Comment                 Gmoji = "\uf075"
	Magnet                  Gmoji = "\uf076"
	ChevronUp               Gmoji = "\uf077"
	ChevronDown             Gmoji = "\uf078"
	Retweet                 Gmoji = "\uf079"
	ShoppingCart            Gmoji = "\uf07a"
	Folder                  Gmoji = "\uf07b"
	FolderOpen              Gmoji = "\uf07c"
	ArrowsVertical          Gmoji = "\uf07d"
	ArrowsHorizontal        Gmoji = "\uf07e"
	BarChart                Gmoji = "\uf080"
	TwitterSquare           Gmoji = "\uf081"
	FacebookSquare          Gmoji = "\uf082"
	CameraRetro             Gmoji = "\uf083"
	Key                     Gmoji = "\uf084"
	Cogs                    Gmoji = "\uf085"
	Comments                Gmoji = "\uf086"
	ThumbsUpOutlined        Gmoji = "\uf087"
	ThumbsDownOutlined      Gmoji = "\uf088"
	StarHalf                Gmoji = "\uf089"
	HeartOutlined           Gmoji = "\uf08a"
	SignOut                 Gmoji = "\uf08b"
	LinkedInSquare          Gmoji = "\uf08c"
	ThumbTack               Gmoji = "\uf08d"
	ExternalLink            Gmoji = "\uf08e"
	SignIn                  Gmoji = "\uf090"
	Trophy                  Gmoji = "\uf091"
	GitHubSquare            Gmoji = "\uf092"
	Upload                  Gmoji = "\uf093"
	LemonOutlined           Gmoji = "\uf094"
	Phone                   Gmoji = "\uf095"
	SquareOutlined          Gmoji = "\uf096"
	BookmarkOutlined        Gmoji = "\uf097"
	PhoneSquare             Gmoji = "\uf098"
	Twitter                 Gmoji = "\uf099"
	Facebook                Gmoji = "\uf09a"
	GitHub                  Gmoji = "\uf09b"
	Unlock                  Gmoji = "\uf09c"
	CreditCard              Gmoji = "\uf09d"
	RSS                     Gmoji = "\uf09e"
	HDD                     Gmoji = "\uf0a0"
	Bullhorn                Gmoji = "\uf0a1"
	Bell                    Gmoji = "\uf0a2"
	Certificate             Gmoji = "\uf0a3"
	HandOutlinedRight       Gmoji = "\uf0a4"
	HandOutlinedLeft        Gmoji = "\uf0a5"
)

/*
O-------------------------------O
O License: MIT 				    O
O-------------------------------O
*/
